name: Build Eden Emulator

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install Vulkan SDK
      run: |
        choco install vulkan-sdk --no-progress
        $vulkanPath = (Get-ChildItem -Path "C:\VulkanSDK" -Directory | Sort-Object Name -Descending | Select-Object -First 1).FullName + "\Bin"
        echo "$vulkanPath" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
        
    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build --config Release -j 4
      
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libvulkan-dev build-essential cmake glslang-tools libxtst-dev libxcursor-dev libxi-dev libxrandr-dev libxss-dev xorg-dev qt6-base-dev qt6-base-private-dev libqt6svg6-dev libxkbcommon-dev libwayland-dev
        
    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DSDL_X11_XTEST=OFF
      
    - name: Build
      run: cmake --build build --config Release -j 4
