name: Build Eden Emulator

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.268.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader, glslang
        vulkan-use-cache: true
        
    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build --config Release -j 4
      
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libvulkan-dev build-essential cmake glslang-tools libxtst-dev libxcursor-dev libxi-dev libxrandr-dev libxss-dev xorg-dev
        
    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DSDL_X11_XTEST=OFF
      
    - name: Build
      run: cmake --build build --config Release -j 4
