name: Build Eden Emulator

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install Vulkan SDK
      run: choco install vulkan-sdk
        
    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build --config Release -j 4
      
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libvulkan-dev build-essential cmake glslang-tools
        
    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build --config Release -j 4
